---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### First, you need to get doi;

If you want to download paper use that package, you need to get the corresponding DOI. First of all, you should be confirm that your IP have the right to download that paper. And if you want to download paper batchly, I suggest you get the DOIs from [Web Of Science](http://login.webofknowledge.com/).

### Second, you need to select the suitable srcFUN of corresponding database. 
If this package have not yet, you can consider to extend the srcFUN, or contact me directly.


Their are two way, we provide to download paper.    
- 1. [aria2](https://aria2.github.io/manual/en/html/), which is same like wget, but can download parallel.  

you should download aria2, and add aria2 path to your system environment variables.
For the convenience of spell in cmd, I rename aira2c as aria2.  

- 2. [httr](https://cran.r-project.org/web/packages/httr/index.html) package by hadley, which download files with the help of `curl`.

`httr`, `curl`, `xml2`, `magrittr`, `stringr` are needed to be installed.
