// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// senslope
SEXP senslope(const NumericVector& y, Nullable<NumericMatrix> x);
RcppExport SEXP _Ipaper_senslope(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(senslope(y, x));
    return rcpp_result_gen;
END_RCPP
}
// Sf
int Sf(NumericVector x);
RcppExport SEXP _Ipaper_Sf(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Sf(x));
    return rcpp_result_gen;
END_RCPP
}
// varS
NumericVector varS(NumericVector x, NumericVector rof, int S);
RcppExport SEXP _Ipaper_varS(SEXP xSEXP, SEXP rofSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rof(rofSEXP);
    Rcpp::traits::input_parameter< int >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(varS(x, rof, S));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Ipaper_senslope", (DL_FUNC) &_Ipaper_senslope, 2},
    {"_Ipaper_Sf", (DL_FUNC) &_Ipaper_Sf, 1},
    {"_Ipaper_varS", (DL_FUNC) &_Ipaper_varS, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Ipaper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
