# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

senslope <- function(x) {
    .Call(`_Ipaper_senslope`, x)
}

Sf <- function(x) {
    .Call(`_Ipaper_Sf`, x)
}

